export const GET_ORDER = 'GET_ORDER '
export const GET_ONE_ORDER = 'GET_ONE_ORDER '
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS '
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL '
export const ADD_ORDER = 'ADD_ORDER '
export const DELETE_ORDER = 'DELET_ORDER'